splunk:
  password: "{{ lookup('env', 'SPLUNK_PASSWORD') }}"
  idxc:
    secret: "{{ lookup('env', 'SPLUNK_IDXC_SECRET') }}"
    search_factor: 1
    replication_factor: 1
    replication_port: 9887
  shc:
    secret: "{{ lookup('env', 'SPLUNK_SHC_SECRET') }}"
    target_url: "{{ lookup('env', 'SPLUNK_SHC_TARGET_URL') | default('https://splunk-sh1:8089', true) }}"
    replication_factor: 2
    replication_port: 9887
