[install]
is_configured = 0

[ui]
is_visible = 1
label = My Splunk App

[launcher]
author = Antigravity
description = Test app for CI/CD pipeline
version = 1.0.0

[id]
my_splunk_app

[package]
id = my_splunk_app


